### ISSUE TITLE
Suck at logo when install 14.1

### ISSUE THREAD

**Issue by tuandn8** [CM12-1-Douglas/android_device_amazon_douglas#4]
I build the rom in branch 14.1 success. But when it is installed to device Douglas by using TWRP, it stuck at loading to OS like in the image.
[Stuck](https://photos.app.goo.gl/tEWdyqLFhnuxueea7)

**Comment by R0rt1z2** [comment]
> I build the rom in branch 14.1 success. But when it is installed to device Douglas by using TWRP, it stuck at loading to OS like in the image.
> [Stuck](https://photos.app.goo.gl/tEWdyqLFhnuxueea7)

Hey there,
Yep, that's an expected behaviour and I'm afraid of it...
The problem it's zygote (`ro.zygote`). For some reason the build system it's setting the property to 32 bit while this device uses the 64 bit one.

As a temporary fix, you can manually unpack the boot image, change the zygote property in default.prop, repack it again and flash the boot image with TWRP:
```
ro.zygote=zygote32_64 --> ro.zygote=zygote64_32
```
I'll try to fix this issue today.
Also, please keep in mind this ROM still has some bugs (camera crashing all the time in the background, DRM, etc).

Regards!

**Comment by R0rt1z2** [comment]
Should be fixed as per https://github.com/douglas-development/android_device_amazon_douglas/commit/86ac4a5de463fbb2490fef6bcf8c99d83e688755
Thanks @488315 :)

**Comment by 488315** [comment]
cap problema

**Comment by tuandn8** [comment]
I built and installed it successfully. Thank you.

**Comment by R0rt1z2** [comment]
> I built and installed it successfully. Thank you.

You're welcome :)
